Feat/#16 blackjackの作成
recursion-teamdev-teamd/card-game-app-for-web-and-mobile pull request #27
Opened 2023-03-31 11:48 UTC by yuki-akiba-jp

modefy player models

2023-03-31 12:55 UTC, kanta1207 requested changes
内容はおkなんですが、コンポーネントはsrc/componentsディレクトリ配下、カスタムフックはsrc/hooksディレクトリにお願いします！
src/pages/blackjackディレクトリはindex.tsxのみにする形で！

2023-03-31 13:10 UTC, yuki-akiba-jp commented
レビューありがとうございます！
コンポネントはとりあえずsrc/components/blackjackに入れることにしました。

2023-03-31 14:29 UTC, kanta1207 approved these changes

2023-04-01 04:07 UTC, colinety approved these changes
確認しました！

2023-04-01 04:07 UTC, merged